name: hello_world
description: A starting point for Dart libraries or applications.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: ^1.82.1
  # path: ^1.8.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
  test: ^1.21.0
